/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.phenixrts.edgeauth;

import com.phenixrts.edgeauth.TokenBuilder;

public class App {
    public String generateToken() {
        return new TokenBuilder()
            .withApplicationId("my-application-id")
            .withSecret("my-secret")
            .expiresInSeconds(3600)
            .forChannel("us-northeast#my-application-id#my-channel.1345")
            .build();
    }

    public static void main(String[] args) {
        System.out.println(new App().generateToken());
    }
}
