/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.phenixrts.edgeauth;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    @Test public void appGeneratesAToken() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.generateToken(), "app should generate a token");
    }
}
